# Configuration for ablation studies

# Training parameters
training:
  total_episodes: 1500
  max_steps_per_episode: 8000
  save_frequency: 50
  eval_frequency: 25
  eval_episodes: 5
  
# DQN Agent parameters
agent:
  learning_rate: 0.0001
  gamma: 0.99
  epsilon_start: 1.0
  epsilon_end: 0.02
  epsilon_decay: 0.998
  target_update_frequency: 1000
  double_dqn: true
  dueling_dqn: true
  noisy_networks: true
  
# Network architecture
network:
  hidden_dims: [512, 512, 256]
  activation: 'relu'
  dropout: 0.1
  
# Experience replay
replay_buffer:
  type: 'prioritized'
  capacity: 200000
  batch_size: 64
  alpha: 0.7
  beta_start: 0.5
  beta_frames: 150000

# Environment settings
environment:
  env_name: 'BreakoutNoFrameskip-v4'
  frame_stack: 4
  frame_skip: 4
  frame_size: [84, 84]
  grayscale: true
  
# Dynamic difficulty
difficulty:
  enable_dynamic: true
  change_frequency: 400
  paddle_speed_range: [0.4, 1.6]
  ball_speed_range: [1.0, 2.5]
  paddle_size_range: [0.6, 1.4]
  brick_regeneration: true
  
# Curriculum learning
curriculum:
  enable: true
  stages:
    - name: 'easy'
      episodes: 200
      difficulty_multiplier: 0.8
    - name: 'normal'
      episodes: 400
      difficulty_multiplier: 1.0
    - name: 'moderate'
      episodes: 400
      difficulty_multiplier: 1.3
    - name: 'hard'
      episodes: 300
      difficulty_multiplier: 1.7
    - name: 'extreme'
      episodes: 200
      difficulty_multiplier: 2.2
  advancement_threshold: 0.75
  
# Adaptation detection
adaptation:
  enable: true
  window_size: 150
  performance_threshold: 0.15
  variance_threshold: 1.2
  kl_threshold: 0.08
  
# Logging and analysis
logging:
  level: 'INFO'
  save_logs: true
  tensorboard: true
  save_models: true
  save_videos: true
  video_frequency: 50

# Output paths
paths:
  base_dir: './ablation_results'
  models_dir: 'models'
  logs_dir: 'logs'
  videos_dir: 'videos'
  plots_dir: 'plots'
