# Extended training configuration for better learning

# Training parameters
training:
  total_episodes: 300
  max_steps_per_episode: 2000
  save_frequency: 25
  eval_frequency: 25
  eval_episodes: 5
  buffer_size: 50000
  min_buffer_size: 1000
  seed: 42

# Network architecture  
network:
  input_shape: [4, 84, 84]
  learning_rate: 0.0005
  gamma: 0.99
  target_update: 500
  batch_size: 32

# Environment settings
environment:
  env_name: 'BreakoutNoFrameskip-v4'
  frame_stack: 4
  frame_skip: 4
  frame_size: [84, 84]
  grayscale: true

# Dynamic difficulty settings
difficulty:
  enable_dynamic: true
  change_frequency: 100
  paddle_speed_range: [0.8, 1.2]
  ball_speed_range: [1.0, 1.3]
  paddle_size_range: [0.9, 1.1]
  brick_regeneration: false

# Curriculum learning
curriculum:
  enable: true
  stages:
    - name: "normal"
      episodes: 50
      difficulty_multiplier: 1.0
    - name: "moderate"  
      episodes: 75
      difficulty_multiplier: 1.1
    - name: "hard"
      episodes: 100
      difficulty_multiplier: 1.2
    - name: "expert"
      episodes: 75
      difficulty_multiplier: 1.3
  advancement_threshold: 0.5

# Adaptation detection
adaptation:
  enable: true
  window_size: 20
  performance_threshold: 0.3
  variance_threshold: 2.0
  kl_threshold: 0.2

# Logging and paths
logging:
  level: "INFO"
  
paths:
  base_dir: "."
  models_dir: "models"
  logs_dir: "logs"
  plots_dir: "plots"
  videos_dir: "videos"
