# Quick test configuration for debugging and development

# Training parameters
training:
  total_episodes: 50
  max_steps_per_episode: 1000
  save_frequency: 10
  eval_frequency: 10
  eval_episodes: 3
  
# DQN Agent parameters
agent:
  learning_rate: 0.001
  gamma: 0.99
  epsilon_start: 0.5
  epsilon_end: 0.1
  epsilon_decay: 0.95
  target_update_frequency: 100
  double_dqn: true
  dueling_dqn: false
  noisy_networks: false
  
# Network architecture
network:
  hidden_dims: [256, 256]
  activation: 'relu'
  dropout: 0.0
  
# Experience replay
replay_buffer:
  type: 'standard'
  capacity: 10000
  batch_size: 32
  
# Environment settings
environment:
  env_name: 'BreakoutNoFrameskip-v4'
  frame_stack: 4
  frame_skip: 4
  frame_size: [84, 84]
  grayscale: true
  
# Dynamic difficulty
difficulty:
  enable_dynamic: true
  change_frequency: 100  # frames
  paddle_speed_range: [0.8, 1.2]
  ball_speed_range: [1.0, 1.3]
  paddle_size_range: [0.9, 1.1]
  brick_regeneration: false
  
# Curriculum learning
curriculum:
  enable: true
  stages:
    - name: 'normal'
      episodes: 20
      difficulty_multiplier: 1.0
    - name: 'moderate'
      episodes: 30
      difficulty_multiplier: 1.1
  advancement_threshold: 0.6
  
# Adaptation detection
adaptation:
  enable: true
  window_size: 20
  performance_threshold: 0.3
  variance_threshold: 2.0
  kl_threshold: 0.2
  
# Logging and analysis
logging:
  level: 'DEBUG'
  save_logs: true
  tensorboard: true
  save_models: false
  save_videos: false
  video_frequency: 25

# Output paths
paths:
  base_dir: './test_results'
  models_dir: 'models'
  logs_dir: 'logs'
  videos_dir: 'videos'
  plots_dir: 'plots'
